# Generated by Django 3.0.5 on 2020-05-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0002_auto_20200530_1500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meeting',
            new_name='Meetings',
        ),
    ]
