# Generated by Django 3.0.5 on 2020-06-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0003_auto_20200530_1516'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meetings',
            table='meetings',
        ),
    ]
