# Generated by Django 3.0.5 on 2020-06-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0005_meetings_meeting_owner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='events',
        ),
    ]
